ALTER TABLE areas ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE areas ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE desired_activations ADD COLUMN IF NOT EXISTS solar_mode TEXT;
DELETE FROM metadata WHERE key = 'dataset_hash';
